### ISSUE TITLE
server returned HTTP status 404 Not Found

### ISSUE THREAD

**Issue by ruaandeysel** [fffonion/tplink-plug-exporter#3]
@fffonion 

I configured prometheus with your prometheus.yml configs. I have updated the IP addresses to my TP link smart plugs.

Prometheus starts but I'm getting "server returned HTTP status 404 Not Found" for my 2 plugs. They are the HS110 model with latest firmware.

Any ideas?

**Comment by fffonion** [comment]
Hi, it looks like a configuration error. Could you share the related prometheus configuration and, if possible, the `kasa` job section in the targets page of prometheus webui?

**Comment by ruaandeysel** [comment]
> Hi, it looks like a configuration error. Could you share the related prometheus configuration and, if possible, the `kasa` job section in the targets page of prometheus webui?

**Comment by ruaandeysel** [comment]
Here's the Prometheus configuration.

`global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
- job_name: kasa
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /scrape
  scheme: http
  static_configs:
  - targets:
    - 192.168.1.14
    - 192.168.1.15
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: 192.168.1.10:9090
    action: replace
- job_name: kasa_exporter
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 192.168.1.10:9090`

Here's an image of the targets

[https://imgur.com/a/0jlmXWJ](url)

**Comment by fffonion** [comment]
OK I think 192.168.1.10:9090 should be changed to host:port of the exporter instead of prometheus.

**Comment by ruaandeysel** [comment]
> OK I think 192.168.1.10:9090 should be changed to host:port of the exporter instead of prometheus.

So Prometheus is running as docker container. Do I need to install the exporter in a different container? If so, do you please have instructions how to install the exporter?

**Comment by ruaandeysel** [comment]
> > OK I think 192.168.1.10:9090 should be changed to host:port of the exporter instead of prometheus.
> 
> So Prometheus is running as docker container. Do I need to install the exporter in a different container? If so, do you please have instructions how to install the exporter?

@fffonion I managed to get the exporter to work. I'm able to view the plug information in the dashboard. 

Thanks for the exporter, dashboard and configs. Really appreciate it.
