### ISSUE TITLE
Grafana: Total Power stat

### ISSUE THREAD

**Issue by jangrewe** [fffonion/tplink-plug-exporter#5]
Hi, thanks for the exporter and dashboard!
I noticed that in the "Total Power" singlestat (top right) you're adding the load (in Watts) to the total power (in Kilowatthours), which kinda doesn't make much sense, as the value would go down with a lower load. Maybe use just the total power in there? 🙂

**Comment by fffonion** [comment]
Yes you are right, that was my misunderstanding and I forgot to update in all graphs. The dashboard has now been updated. Thanks for reporting!
