### ISSUE TITLE
License / copyright information

### ISSUE THREAD

**Issue by jelmer** [fffonion/tplink-plug-exporter#6]
This project currently doesn't have a license declared or mention of who owns the copyright. Is there any chance you could bundle a file describing the license?

Thanks :)

**Comment by fffonion** [comment]
@jelmer Thanks for the notice, I have now added a license.

**Comment by jelmer** [comment]
On Mon, Jun 22, 2020 at 01:05:29PM +0000, Wangchong Zhou wrote:
> @jelmer Thanks for the notice, I have now added a license.
Thanks!
